-- Create STUDENT table
CREATE TABLE STUDENT (
  STUDENT_ID NUMBER(4) PRIMARY KEY,
  STUDENT_NAME VARCHAR2(50),
  DEPT VARCHAR2(30),
  JOIN_YEAR NUMBER(4)
);

-- Create COURSE table
CREATE TABLE COURSE (
  COURSE_ID NUMBER(4) PRIMARY KEY,
  COURSE_NAME VARCHAR2(50),
  MAX_MARKS NUMBER(3)
);

-- Create MARKS table
CREATE TABLE MARKS (
  STUDENT_ID NUMBER(4),
  COURSE_ID NUMBER(4),
  MARKS_OBTAINED NUMBER(3),
  CONSTRAINT fk_student FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  CONSTRAINT fk_course FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);
