-- 1️⃣ List all students with their average marks
SELECT s.STUDENT_NAME, ROUND(AVG(m.MARKS_OBTAINED),2) AS AVG_MARKS
FROM STUDENT s
JOIN MARKS m ON s.STUDENT_ID = m.STUDENT_ID
GROUP BY s.STUDENT_NAME;

-- 2️⃣ Find the top-performing student
SELECT s.STUDENT_NAME, SUM(m.MARKS_OBTAINED) AS TOTAL
FROM STUDENT s
JOIN MARKS m ON s.STUDENT_ID = m.STUDENT_ID
GROUP BY s.STUDENT_NAME
ORDER BY TOTAL DESC FETCH FIRST 1 ROW ONLY;

-- 3️⃣ Department-wise average score
SELECT s.DEPT, ROUND(AVG(m.MARKS_OBTAINED),2) AS AVG_DEPT_SCORE
FROM STUDENT s
JOIN MARKS m ON s.STUDENT_ID = m.STUDENT_ID
GROUP BY s.DEPT;
